// <auto-generated />
namespace Pidev.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class gg000 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gg000));
        
        string IMigrationMetadata.Id
        {
            get { return "201912012006045_gg000"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
